source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KSKeyboardHandler_Example', :exclusive => true do
  pod 'KSKeyboardHandler', :path => '../'
end

target 'KSKeyboardHandler_Tests', :exclusive => true do
  pod 'KSKeyboardHandler', :path => '../'

  pod 'FBSnapshotTestCase'
end
